using System.Collections.Generic;

namespace InfectedRose.Interface
{
    /// <summary>
    /// A list of items that were generated by the mod and put into the main resource directory
    ///
    /// These items are deleted upon startup.
    /// </summary>
    public class Artifacts : Dictionary<string, string>
    {
        
    }
}